#!/bin/sh

# --- AUTOSTART SCRIPT FOR BERSERK ARCH ---

# Generate dynamic pipe menu (updates automatically when opened)
obmenu-generator -p 2>/dev/null
openbox --reconfigure &

# Start the panel
# tint2 &

# Start the wallpaper manager
# (while true; do
#   feh --bg-fill "/usr/share/backgrounds/berserkarch/berserkarch.png"
#   sleep 10
# done) &
# feh --bg-fill "/usr/share/backgrounds/berserkarch/berserkarch.png" &
xsettingsd &
/usr/lib/polkit-kde-authentication-agent-1 &
/usr/bin/spice-vdagent &

## compositor
xcompmgr -c -f -F -D 1 &

## start polybar
~/.config/polybar/launch.sh &
pamac-tray &
firewall-applet &
/usr/share/berserkarch/conky/scripts/launch.sh & # berserk-conky <- package needs to be installed

## starting dconf to connect to gtk3/4 services
/usr/lib/dconf-service &
xrandr --output Virtual-1 --mode 1920x1080 & # optional - remove if using something else
nitrogen --restore &
